### ISSUE TITLE
Security Manager strictly needed?

### ISSUE THREAD

**Issue by HeikoMueller** [cckellogg/pulsar-vault#1]
Hi. First of all, thank you for this nice plugin!

I was wondering if – in VaultAuthenticationProvider.java – this

            SecurityManager s = System.getSecurityManager();
            group = (s != null) ? s.getThreadGroup() :
                    Thread.currentThread().getThreadGroup();

can safely be replaced with 

group = Thread.currentThread().getThreadGroup();

since SecruityManager is deprecated now? Is there a particular necessety for keeping this in the code or can it safely be removed for forward compatibility?

**Comment by cckellogg** [comment]
Hi and thanks.  

The code was copied from the `java.util.concurrent.Executors` class and modified to add a constructor with a name prefix so it's easier to see which threads the plugin is using. I looked at the latest openJDK source code and it added a suppress warning annotation but I think it can be safely removed and replaced with what you suggested. Feel free to submit a PR.
